### ISSUE TITLE
Change timeline rod color

### ISSUE THREAD

**Issue by sambhavnrana** [TechnicalTeam-BVCOENM/Abhiyaan-website#19]
![image](https://github.com/TechnicalTeam-BVCOENM/Abhiyaan-website/assets/89438969/456a0463-a021-4d0b-b6e3-5d70571e0678)

**Comment by sambhavnrana** [comment]
@rohitbaing08 Pls do the needful ASAP

**Comment by psantosh16** [comment]
Fixed
